image: jangrewe/gitlab-ci-android

services:
  - mongo:latest

variables:
  PROJECT_NAME: treasure_hunter
  PROJECT_VERSION: 0.0.1
  localhost: $mongo

before_script:
  - git remote set-url origin https://$GIT_USERR:$GIT_ACCESSS@gitlab.com/$CI_PROJECT_PATH.git
  - git config --global user.email 'anestis.zioulis@outlook.com'
  - git config --global user.name 'aneziou'

stages:
  - build
  - release

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - ping mongo -c 5
    - echo $localhost
    - echo $mongo
    - sed -i 's/CI_PIPELINE_ID/${CI_PIPELINE_ID}/g' pom.xml
    - sed -i 's/PROJECT_VERSION/${PROJECT_VERSION}/g' pom.xml
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar



assembleRelease:
  stage: release
  only:
    - testCI
  script:
    - git log --pretty=format:"%cd %s" > changelog.txt
    - git tag -a $PROJECT_NAME-$PROJECT_VERSION-$CI_PIPELINE_ID -F changelog.txt
    - git push origin $PROJECT_NAME-$PROJECT_VERSION-$CI_PIPELINE_ID
    - |
      curl --fail --output "/dev/null" --silent --show-error --write-out "HTTP response: ${http_code}\n\n" \
        --data "{\"tag_name\": \"${PROJECT_NAME}-${PROJECT_VERSION}-${CI_PIPELINE_ID}\", \"name\": \"${PROJECT_NAME}-${PROJECT_VERSION}-${CI_PIPELINE_ID}\",  \"assets\": { \"links\": [{ \"name\": \"release\", \"url\": \"https://gitlab.com/aneziou/treasure_hunter/-/jobs/${CI_JOB_ID}/artifacts/download\" }] }, \"description\": \"No release notes.\"}" \
        --header "Content-Type: application/json" \
        --header "Private-Token: ${GIT_ACCESSS}" \
        --request POST \
        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases"
  artifacts:
    paths:
      - target/*.jar
      - changelog.txt